version: "3"

env:
  STEAM_APPS: D:\SteamLibrary\steamapps
  STEAM_OS: '{{if eq OS "windows"}}Win64{{else}}Linux{{end}}'

tasks:
  build:
    cmds:
      - curl -k -LO https://github.com/pardeike/HarmonyRimWorld/releases/latest/download/HarmonyMod.zip
      - 7z x -y HarmonyMod.zip -opackages
      - dotnet build ./Source/CustomFonts/CustomFonts.sln -c "Release 1.5"

  release:
    cmds:
      - git archive --format=tar.gz HEAD -o custom-fonts.tar.gz
      - tar zxvf custom-fonts.tar.gz -C "${STEAM_APPS}/Common/RimWorld/Mods/rw-customfonts/"
      - |
        cd "${STEAM_APPS}/Common/RimWorld/Mods/rw-customfonts/"
        rm Taskfile.*
        rm .git*
