version: "3"

dotenv: [".env"]

env:
  STEAM_OS: '{{if eq OS "windows"}}RimWorldWin64_Data{{else}}{{if eq OS "linux"}}RimWorldLinux_Data{{else}}RimWorldMac.app/Contents/Resources/Data{{end}}{{end}}'

tasks:
  prepare:
    desc: prepare the environment
    cmds:
      - curl -LO https://github.com/pardeike/HarmonyRimWorld/releases/latest/download/HarmonyMod.zip
      - cmd: 7z x -y HarmonyMod.zip -opackages
        platforms: [windows, linux]
      - cmd: 7zz x -y HarmonyMod.zip -opackages
        platforms: [darwin]

  build:
    desc: build the project
    env:
      ProjectDir: "{{.USER_WORKING_DIR}}/Source/CustomFonts"
    cmds:
      - echo ${STEAM_OS}
      - echo ${ProjectDir}
      - |
        export STEAM_APPS=${STEAM_APPS_1_4}
        dotnet build ./Source/CustomFonts/CustomFonts.sln -c "Release 1.4"
      - |
        export STEAM_APPS=${STEAM_APPS_1_5}
        dotnet build ./Source/CustomFonts/CustomFonts.sln -c "Release 1.5"
      - |
        export STEAM_APPS=${STEAM_APPS_1_6}
        dotnet build ./Source/CustomFonts/CustomFonts.sln -c "Release 1.6"

  export:
    cmds:
      - cmd: robocopy 1.4/Assemblies "${STEAM_APPS}/common/RimWorld/Mods/rw-customfonts/1.4/Assemblies" /E /NFL /NDL /NJH /NJS || exit 0
        platforms: [windows]
      - cmd: robocopy 1.5/Assemblies "${STEAM_APPS}/common/RimWorld/Mods/rw-customfonts/1.5/Assemblies" /E /NFL /NDL /NJH /NJS || exit 0
        platforms: [windows]
      - cmd: robocopy 1.6/Assemblies "${STEAM_APPS}/common/RimWorld/Mods/rw-customfonts/1.6/Assemblies" /E /NFL /NDL /NJH /NJS || exit 0
        platforms: [windows]
      - cmd: cp -rf 1.4/Assemblies/* "${STEAM_APPS}/common/RimWorld/Mods/rw-customfonts/1.4/Assemblies/"
        platforms: [linux]
      - cmd: cp -rf 1.5/Assemblies/* "${STEAM_APPS}/common/RimWorld/Mods/rw-customfonts/1.5/Assemblies/"
        platforms: [linux]
      - cmd: cp -rf 1.6/Assemblies/* "${STEAM_APPS}/common/RimWorld/Mods/rw-customfonts/1.6/Assemblies/"
        platforms: [linux]
      - cmd: cp -rf 1.4/Assemblies/* "${STEAM_APPS}/common/RimWorld/RimWorldMac.app/Mods/rw-customfonts/1.4/Assemblies/"
        platforms: [darwin]
      - cmd: cp -rf 1.5/Assemblies/* "${STEAM_APPS}/common/RimWorld/RimWorldMac.app/Mods/rw-customfonts/1.5/Assemblies/"
        platforms: [darwin]
      - cmd: cp -rf 1.6/Assemblies/* "${STEAM_APPS}/common/RimWorld/RimWorldMac.app/Mods/rw-customfonts/1.6/Assemblies/"
        platforms: [darwin]
      - cmd: robocopy Languages "${STEAM_APPS}/common/RimWorld/Mods/rw-customfonts/Languages" /E /NFL /NDL /NJH /NJS || exit 0
        platforms: [windows]
      - cmd: cp -rf Languages/* "${STEAM_APPS}/common/RimWorld/Mods/rw-customfonts/Languages/"
        platforms: [linux]
      - cmd: cp -rf Languages/* "${STEAM_APPS}/common/RimWorld/RimWorldMac.app/Mods/rw-customfonts/Languages/"
        platforms: [darwin]

  build_and_export:
    desc: build and export the project
    cmds:
      - task: build
      - task: export

  release:
    cmds:
      - git archive --format=tar.gz HEAD -o custom-fonts.tar.gz
      - cmd: |
          mkdir "${STEAM_APPS}/common/RimWorld/Mods/rw-customfonts/" || true
          tar zxvf custom-fonts.tar.gz -C "${STEAM_APPS}/common/RimWorld/Mods/rw-customfonts/"
        platforms: [windows]
      - cmd: |
          mkdir -p "${STEAM_APPS}/common/RimWorld/Mods/rw-customfonts/"
          tar zxvf custom-fonts.tar.gz -C "${STEAM_APPS}/common/RimWorld/Mods/rw-customfonts/"
        platforms: [linux]
      - cmd: |
          mkdir -p "${STEAM_APPS}/common/RimWorld/RimWorldMac.app/Mods/rw-customfonts/"
          tar zxvf custom-fonts.tar.gz -C "${STEAM_APPS}/common/RimWorld/RimWorldMac.app/Mods/rw-customfonts/"
        platforms: [darwin]
      - cmd: |
          cd "${STEAM_APPS}/common/RimWorld/Mods/rw-customfonts/"
          rm Taskfile.*
          rm .git*
          rm .env.sample
          rm .pre-commit-config.yaml
          rm .editorconfig
          rm -rf Source
        platforms: [windows, linux]
      - cmd: |
          cd "${STEAM_APPS}/common/RimWorld/RimWorldMac.app/Mods/rw-customfonts/"
          rm Taskfile.*
          rm .git*
          rm .env.sample
          rm .pre-commit-config.yaml
          rm .editorconfig
          rm -rf Source
        platforms: [darwin]

  rider:
    cmds:
      - rider .

  code:
    cmds:
      - code .

  format:
    desc: format
    cmds:
      - dotnet format ./Source/CustomFonts/CustomFonts.sln

  version:
    desc: get current version
    cmds:
      - |
        export CURRENT_VERSION=$(monodis --assembly "${STEAM_APPS}/common/RimWorld/${STEAM_OS}/Managed/Assembly-CSharp.dll" | grep "Version:" | sed 's/.*Version: *\([0-9]*\.[0-9]*\.[0-9]*\).*/\1/' | tr -d '\r')
        echo "Current version: ${CURRENT_VERSION}"

  backup:
    desc: backup current version
    cmds:
      - cmd: |
          export CURRENT_VERSION=$(monodis --assembly "${STEAM_APPS}/common/RimWorld/${STEAM_OS}/Managed/Assembly-CSharp.dll" | grep "Version:" | sed 's/.*Version: *\([0-9]*\.[0-9]*\.[0-9]*\).*/\1/' | tr -d '\r')
          echo "Current version: <${CURRENT_VERSION}>"
          mkdir -p "${STEAM_APPS}/old/RimWorld/${CURRENT_VERSION}/common/RimWorld/" || true
          rsync -avz --delete "${STEAM_APPS}/common/RimWorld/" "${STEAM_APPS}/old/RimWorld/${CURRENT_VERSION}/common/RimWorld/"
        platforms: [darwin, linux]
      - cmd: |
          export CURRENT_VERSION=$(monodis --assembly "${STEAM_APPS}/common/RimWorld/${STEAM_OS}/Managed/Assembly-CSharp.dll" | grep "Version:" | sed 's/.*Version: *\([0-9]*\.[0-9]*\.[0-9]*\).*/\1/' | tr -d '\r')
          echo "Current version: <${CURRENT_VERSION}>"
          mkdir "${STEAM_APPS}/old/RimWorld/${CURRENT_VERSION}/common/RimWorld/" || true
          robocopy "${STEAM_APPS}/common/RimWorld" "${STEAM_APPS}/old/RimWorld/${CURRENT_VERSION}/common/RimWorld" /MIR /NFL /NDL /NJH /NJS
        platforms: [windows]
